version: '3'
services:
  web:
    image: "docker-flask"
    build: .
    ports:
     - "8080:80"
  mongo:
    image: "mongo"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
  kafka:
    image: "kafkamanager/kafka-manager"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s

